/*
 OpenCL wrapper code
 Copyright 2019-2021 Zhang Maiyun <myzhang1029@hotmail.com>

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

#ifdef __APPLE__
#include <OpenCL/OpenCL.h>
#else
#include <CL/cl.h>
#endif
#include <stdio.h>
#include <string.h>

#include "tool.h"
/* Generated by Makefile */
#include "prog.h"

#define CHECK_ERROR(msg)                                                       \
    do                                                                         \
    {                                                                          \
        if (stat != CL_SUCCESS)                                                \
        {                                                                      \
            fprintf(stderr, (msg));                                            \
            exit(1);                                                           \
        }                                                                      \
    } while (0)

int main(void)
{
    const size_t rand_samples = 4294967295ull;
    const size_t memsize = 128000;
    const float r = 5.0f;
    const float scaled_r = r * rand_samples;
    size_t inside = 0;
    cl_platform_id *plats;
    cl_device_id **devices;
    cl_device_id to_use;
    cl_context ctx;
    cl_command_queue cq;
    cl_program program;
    cl_mem outmem;
    cl_kernel kernel;
    cl_int stat;
    cl_uint *results;

    plats = get_platforms();
    if (!plats)
        return 2;
    devices = get_devices(plats[0]);
    free(plats);
    if (devices[1])
        to_use = devices[1][0];
    else if (devices[0])
        to_use = devices[0][0];
    else
        return 2;
    ctx = clCreateContext(NULL, 1, &to_use, NULL, NULL, &stat);
    CHECK_ERROR("Error creating context\n");
    cq = clCreateCommandQueue(ctx, to_use, 0, &stat);
    CHECK_ERROR("Error creating command queue\n");

    program = clCreateProgramWithSource(ctx, 1, &prog, NULL, &stat);
    stat |= clBuildProgram(program, 1, &to_use, "-Werror", NULL, NULL);
    if (stat != CL_SUCCESS)
    {
        size_t len;
        char buffer[2048];
        fprintf(stderr, "Error building program\n");
        clGetProgramBuildInfo(program, to_use, CL_PROGRAM_BUILD_LOG,
                              sizeof(buffer), buffer, &len);
        fprintf(stderr, "%s\n", buffer);
        exit(1);
    }

    kernel = clCreateKernel(program, "monte_carlo", &stat);
    CHECK_ERROR("Error creating kernel\n");

    results = calloc(memsize, sizeof(cl_uint));

    /* Prepare parameters */
    outmem = clCreateBuffer(ctx, CL_MEM_WRITE_ONLY | CL_MEM_COPY_HOST_PTR,
                            sizeof(cl_uint) * memsize, results, &stat);
    CHECK_ERROR("Error creating buffer\n");

    /* radius */
    stat = clSetKernelArg(kernel, 0, sizeof(float), (void *)&scaled_r);
    /* The output list */
    stat |= clSetKernelArg(kernel, 1, sizeof(cl_mem), (void *)&outmem);
    /* Size of outmem as modulo */
    stat |= clSetKernelArg(kernel, 2, sizeof(size_t), (void *)&memsize);
    CHECK_ERROR("Error setting args\n");
    /* Issue calls */
    stat = clEnqueueNDRangeKernel(cq, kernel, 1, NULL, &rand_samples, NULL, 0,
                                  NULL, NULL);
    CHECK_ERROR("Error executing kernel\n");
    /* Wait all */
    clFinish(cq);
    stat =
        clEnqueueReadBuffer(cq, outmem, CL_TRUE, 0, sizeof(cl_uint) * memsize,
                            results, 0, NULL, NULL);
    CHECK_ERROR("Error reading output array\n");
    for (size_t i = 0; i < memsize; ++i)
    {
        inside += results[i];
    }

    printf("%zu/%zu\n", inside, rand_samples);
    printf("%g\n", inside / (double)rand_samples * 4 * r * r);

    /* Clean up */
    free(results);
    stat = clReleaseMemObject(outmem);
    stat |= clReleaseKernel(kernel);
    stat |= clReleaseProgram(program);
    stat |= clReleaseCommandQueue(cq);
    stat |= clReleaseContext(ctx);
    free_devices(devices);
    return 0;
}
